// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyMoviesManager.Models;

public partial class Actors
{
    public int ActorId { get; set; }

    public int? MovieId { get; set; }

    public string ActorName { get; set; }

    public virtual Movies Movie { get; set; }
}